In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input,Lambda,Dense,Conv2D,Flatten,MaxPooling2D
from tensorflow.keras.models import Model,load_model
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img


In [3]:
classifier=Sequential()
classifier.add(Conv2D(filters=16,kernel_size=2,padding="same",activation="relu",input_shape=(224,224,3)))
classifier.add(MaxPooling2D(pool_size=2))
classifier.add(Conv2D(filters=32,kernel_size=2,padding="same",activation="relu"))
classifier.add(MaxPooling2D(pool_size=2))
classifier.add(Conv2D(filters=64,kernel_size=2,padding="same",activation="relu"))
classifier.add(MaxPooling2D(pool_size=2))
classifier.add(Flatten())
classifier.add(Dense(units=500,activation="relu"))
classifier.add(Dense(units=2,activation="softmax"))
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 224, 224, 16)      208       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 112, 112, 16)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 112, 112, 32)      2080      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 56, 56, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 56, 56, 64)        8256      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 28, 28, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 50176)             0

In [4]:
classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [5]:
train_data=ImageDataGenerator(rescale=1/255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_data=ImageDataGenerator(rescale=1/255)

In [6]:
train=train_data.flow_from_directory('Dataset/Train',target_size=(224,224),batch_size=32,class_mode='categorical')
test=test_data.flow_from_directory('Dataset/Test',target_size=(224,224),batch_size=32,class_mode='categorical')

Found 416 images belonging to 2 classes.
Found 134 images belonging to 2 classes.


In [7]:
run=classifier.fit_generator(train,validation_data=test,epochs=25,steps_per_epoch=len(train),validation_steps=len(test))

Epoch 1/25
13/13 [==============================] - 15s 1s/step - loss: 0.9078 - accuracy: 0.5072 - val_loss: 0.6891 - val_accuracy: 0.5224
Epoch 2/25
13/13 [==============================] - 14s 1s/step - loss: 0.5854 - accuracy: 0.7019 - val_loss: 0.7687 - val_accuracy: 0.4328
Epoch 3/25
13/13 [==============================] - 14s 1s/step - loss: 0.4707 - accuracy: 0.7548 - val_loss: 1.3707 - val_accuracy: 0.2537
Epoch 4/25
13/13 [==============================] - 13s 1s/step - loss: 0.4293 - accuracy: 0.7740 - val_loss: 1.0561 - val_accuracy: 0.3134
Epoch 5/25
13/13 [==============================] - 13s 1s/step - loss: 0.3677 - accuracy: 0.8173 - val_loss: 1.7352 - val_accuracy: 0.3731
Epoch 6/25
13/13 [==============================] - 13s 1s/step - loss: 0.4161 - accuracy: 0.8053 - val_loss: 1.0210 - val_accuracy: 0.3881
Epoch 7/25
13/13 [==============================] - 13s 1s/step - loss: 0.3572 - accuracy: 0.8413 - val_loss: 0.8249 - val_accuracy: 0.4478
Epoch 8/25
13/13 [==

In [8]:
classifier.save('cnn_model.h5')

In [9]:
pred=classifier.predict(test)
pred

array([[1.32626928e-02, 9.86737311e-01],
       [9.99990702e-01, 9.33715000e-06],
       [9.89001036e-01, 1.09989215e-02],
       [7.30424821e-02, 9.26957548e-01],
       [9.97921884e-01, 2.07816926e-03],
       [9.98533845e-01, 1.46609952e-03],
       [1.17759563e-01, 8.82240474e-01],
       [1.37963239e-02, 9.86203671e-01],
       [9.99229789e-01, 7.70237006e-04],
       [9.99129355e-01, 8.70611577e-04],
       [9.99999881e-01, 9.57641788e-08],
       [9.99986172e-01, 1.38617133e-05],
       [9.95923996e-01, 4.07599472e-03],
       [1.94494858e-01, 8.05505216e-01],
       [1.79851502e-01, 8.20148468e-01],
       [9.98956561e-01, 1.04337593e-03],
       [4.84593771e-02, 9.51540649e-01],
       [2.38485318e-02, 9.76151407e-01],
       [5.11108577e-01, 4.88891512e-01],
       [8.50461483e-01, 1.49538517e-01],
       [9.99038458e-01, 9.61532118e-04],
       [7.97912478e-01, 2.02087596e-01],
       [5.94582081e-01, 4.05417889e-01],
       [9.99371707e-01, 6.28300593e-04],
       [3.037415

In [10]:
pred=np.argmax(pred,axis=1)
pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1])

In [11]:
classifier=load_model('cnn_model.h5')

In [12]:
from tensorflow.keras.preprocessing import image
img=image.load_img('Dataset/Test/Parasite/C39P4thinF_original_IMG_20150622_105554_cell_10.png',target_size=(224,224))

In [13]:
x=image.img_to_array(img)
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [14]:
x=x/225
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 224, 224, 3)

In [15]:
classifier.predict(img_data)

array([[1., 0.]], dtype=float32)

In [16]:
p=np.argmax(classifier.predict(img_data), axis=1)

In [17]:
if(p==1):
    print("Uninfected")
else:
    print("Infected")

Infected
